const businessData = [
  {
    image: "../images/Fratellies.jpeg",
    name: "Fratellies",
    address: "134 Right here ln",
    city: "Our Town",
    state: "New York",
    zipCode: "24567",
    category: "Italian",
    rating: "4.5",
    reviewCount: 1200,
  },
  {
    image: `../images/FishNuggies.jpeg`,
    name: "Fish Nuggies",
    address: "50 fades of rey",
    city: "Buckees",
    state: "Gulf of Mexico",
    zipCode: "20946",
    category: "Fishy Nuggets",
    rating: "5.5",
    reviewCount: 42000,
  },
  {
    image: "../images/MeatSammies.jpeg",
    name: "Meat Sammies",
    address: "100 Percent Elk circle",
    city: "Rock Hill",
    state: "Gulf of Mexico",
    zipCode: "38501",
    category: "Burgers",
    rating: "5.5",
    reviewCount: 78,
  },
  {
    image: "../images/Taquisimo.jpeg",
    name: "Taquisimo",
    address: "90 Down There dr",
    city: "Their Town",
    state: "Border",
    zipCode: "10948",
    category: "Tacos y mas",
    rating: "2.5",
    reviewCount: 3000,
  },
  {
    image: "../images/Buckees.jpeg",
    name: "Buckees",
    address: "34 Rest Stop rd",
    city: "Montana",
    state: "SC",
    zipCode: "28374",
    category: "Junk and Ghas",
    rating: "23.5",
    reviewCount: 40000,
  },
]

export default businessData
