const businesses = [
  {
    image: "",
    name: "Fratellies",
    address: "134 Right here ln",
    city: "Our Town",
    state: "New York",
    zipCode: "24567",
    category: "Italian",
    rating: "4.5",
    reviewCount: 1200,
  },
  {
    image: "",
    name: "Adobo",
    address: "90 Over There dr",
    city: "Their Town",
    state: "Hobbiton",
    zipCode: "10948",
    category: "French",
    rating: "2.5",
    reviewCount: 3000,
  },
  {
    image: "",
    name: "Meat Sammies",
    address: "100 Percent Elk circle",
    city: "Rock Hill",
    state: "Gulf of Mexico",
    zipCode: "38501",
    category: "Burgers",
    rating: "5.5",
    reviewCount: 78,
  },
  {
    image: "",
    name: "Fish Nuggies",
    address: "50 fades of rey",
    city: "Buckees",
    state: "Gulf of Mexico",
    zipCode: "20946",
    category: "Fish and Nuggets",
    rating: "5.5",
    reviewCount: 42000,
  },
]

export default businesses
